name: Trip Tracker

options:
  bundleIdPrefix: dev.mendia
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    DEAD_CODE_STRIPPING: YES
    ENABLE_MODULE_VERIFIER: YES
    MODULE_VERIFIER_SUPPORTED_LANGUAGES: "objective-c objective-c++"
    MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: "gnu17 gnu++20"

targets:
  Trip Tracker:
    type: application
    platform: iOS
    sources:
      - path: Trip Tracker
    settings:
      base:
        PRODUCT_NAME: Trip Tracker
        PRODUCT_BUNDLE_IDENTIFIER: dev.mendia.TripTracker
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_ASSET_PATHS: '"Trip Tracker/Preview Content"'
        SWIFT_EMIT_LOC_STRINGS: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "0.1.0"
